import "./globals.css"
import { Poppins, Open_Sans, Roboto } from "next/font/google"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
})

const open_sans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
})

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-bgprimary`}>{children}</body>
    </html>
  )
}
